name: curl
base: core24
version: '8.16.0'
license: curl
summary: command line tool and library for transferring data with URLs
description: |
  A command line tool and library for transferring data with URL syntax, supporting DICT, FILE, FTP, FTPS, GOPHER, GOPHERS, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, MQTT, POP3, POP3S, RTMP, RTMPS, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET, TFTP, WS and WSS. libcurl offers a myriad of powerful features.
platforms:
  amd64:
  arm64:
  armhf:
grade: stable
confinement: strict
plugs:
  dot-curlrc:
    interface: personal-files
    read:
      - $HOME/.curlrc
apps:
  curl:
    command: usr/local/bin/wrapper.sh
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/lib
    plugs:
      - network
      - home
      - dot-curlrc
  wcurl:
    command: usr/local/bin/wcurl
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/lib
    plugs:
      - network
      - home
      - dot-curlrc
  openssl:
    command: usr/local/bin/openssl
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/lib
    plugs:
      - network
      - network-bind
      - home
  snap-acked:
    command: usr/local/bin/snap_ack.sh
    plugs:
      - home
parts:
  curl:
    after: [nghttp3]
    plugin: autotools
    source: https://curl.se/download/curl-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
    autotools-configure-parameters:
      - --with-openssl
      - --with-gssapi
      - --with-libssh2
      - --with-nghttp2
      - --with-nghttp3
      - --with-openssl-quic
      - --enable-versioned-symbols
    build-packages:
      # - libssl-dev
      - libssh2-1-dev
      - libbrotli-dev
      - libidn2-dev
      - librtmp-dev
      - libldap2-dev
      - libnghttp2-dev
      - libpsl-dev
      - libkrb5-dev
      - libzstd-dev
    stage-packages:
      - libbrotli1
      - libidn2-0
      - librtmp1
      - libldap2
      - libssh2-1t64
      - libnghttp2-14
      - libpsl5t64
      - libkrb5-3
      - libzstd1
    prime:
      - -usr/local/share/man
  openssl:
    plugin: make
    source: https://github.com/openssl/openssl/releases/download/openssl-3.5.3/openssl-3.5.3.tar.gz
    override-build: |
      # fix build error on armhf. https://github.com/openssl/openssl/issues/21630
      if [ x$(dpkg --print-architecture) == x'armhf' ];then
        ./Configure linux-armv4 --prefix=/usr/local --libdir=lib
      else
        ./Configure --prefix=/usr/local --libdir=lib
      fi
      craftctl default
    prime:
      - -usr/local/share/doc/openssl
      - -usr/local/share/man
  nghttp3:
    after: [openssl]
    plugin: autotools
    source: https://github.com/ngtcp2/nghttp3/releases/download/v1.11.0/nghttp3-1.11.0.tar.gz
    autotools-configure-parameters:
      - --enable-lib-only
    build-packages:
      - pkg-config
  scripts:
    plugin: dump
    source: scripts/
    organize:
      '*': usr/local/bin/
