name: curl
base: core24
version: '8.17.0'
license: curl
summary: command line tool and library for transferring data with URLs
description: |
  A command line tool and library for transferring data with URL syntax, supporting DICT, FILE, FTP, FTPS, GOPHER, GOPHERS, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, MQTT, POP3, POP3S, RTMP, RTMPS, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET, TFTP, WS and WSS. libcurl offers a myriad of powerful features.
platforms:
  amd64:
  arm64:
  armhf:
grade: stable
confinement: strict
plugs:
  dot-curlrc:
    interface: personal-files
    read:
      - $HOME/.curlrc
apps:
  curl:
    command: usr/local/bin/wrapper.sh
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/lib
      CURL_HOME: $SNAP_USER_COMMON
    plugs:
      - network
      - home
      - dot-curlrc
  openssl:
    command: usr/local/bin/openssl
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/lib
    plugs:
      - network
      - network-bind
      - home
  snap-acked:
    command: usr/local/bin/snap_ack.sh
    plugs:
      - home
parts:
  curl:
    after:
      - nghttp2
      - nghttp3
      - openssl
    plugin: autotools
    source: https://curl.se/download/curl-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
    autotools-configure-parameters:
      - --with-openssl
      - --with-gssapi
      - --with-libssh2
      - --with-nghttp2
      - --with-nghttp3
      - --with-openssl-quic
      - --enable-versioned-symbols
      - --disable-static
      - --disable-docs
    build-packages:
      # - libssl-dev
      - libssh2-1-dev
      - libbrotli-dev
      - libidn2-dev
      - librtmp-dev
      - libldap2-dev
      # - libnghttp2-dev
      - libpsl-dev
      - libkrb5-dev
      - libzstd-dev
    stage-packages:
      - libbrotli1
      - libidn2-0
      - librtmp1
      - libldap2
      - libssh2-1t64
      # - libnghttp2-14
      - libpsl5t64
      - libkrb5-3
      - libzstd1
    prime:
      - -usr/share/doc
      - -usr/local/include
  openssl:
    plugin: make
    source: https://github.com/openssl/openssl/releases/download/openssl-3.6.0/openssl-3.6.0.tar.gz
    override-build: |
      # fix build error on armhf. https://github.com/openssl/openssl/issues/21630
      if [ x$(dpkg --print-architecture) == x'armhf' ];then
        ./Configure linux-armv4 --prefix=/usr/local --libdir=lib
      else
        ./Configure --prefix=/usr/local --libdir=lib
      fi
      craftctl default
    prime:
      - -usr/local/include
      - -usr/local/lib/libcrypto.a
      - -usr/local/lib/libssl.a
      - -usr/local/share/doc
      - -usr/local/share/man
  nghttp2:
    plugin: cmake
    source: https://github.com/nghttp2/nghttp2/releases/download/v1.68.0/nghttp2-1.68.0.tar.gz
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DENABLE_LIB_ONLY=ON
      - -DENABLE_DOC=OFF
    build-packages:
      - pkg-config
    prime:
      - -usr/local/include
  nghttp3:
    plugin: cmake
    source: https://github.com/ngtcp2/nghttp3/releases/download/v1.13.1/nghttp3-1.13.1.tar.gz
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DENABLE_LIB_ONLY=ON
      - -DENABLE_STATIC_LIB=OFF
    build-packages:
      - pkg-config
    prime:
      - -usr/local/include
      - -usr/local/share/doc
  scripts:
    plugin: dump
    source: scripts/
    organize:
      '*': usr/local/bin/
