name: curl
base: core24
version: '8.12.0'
license: curl
summary: command line tool and library for transferring data with URLs
description: |
  A command line tool and library for transferring data with URL syntax, supporting DICT, FILE, FTP, FTPS, GOPHER, GOPHERS, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, MQTT, POP3, POP3S, RTMP, RTMPS, RTSP, SCP, SFTP, SMB, SMBS, SMTP, SMTPS, TELNET, TFTP, WS and WSS. libcurl offers a myriad of powerful features.
  
platforms:
  amd64:
  arm64:
  armhf:

grade: stable
confinement: strict

plugs:
  dot-curlrc:
    interface: personal-files
    read:
      - $HOME/.curlrc

apps:
  curl:
    command: usr/local/bin/curl
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/lib
    plugs:
      - network
      - home
      - dot-curlrc

parts:
  curl:
    after: [nghttp3]
    plugin: autotools
    source: .
    override-pull: |
      wget https://curl.se/download/curl-${SNAPCRAFT_PROJECT_VERSION}.tar.gz -O curl-src.tar.gz
      tar zxf curl-src.tar.gz --strip-components=1
      rm -f curl-src.tar.gz
    autotools-configure-parameters:
      - --with-openssl
      - --with-gssapi
      - --with-libssh2
      - --with-nghttp2
      # - --with-nghttp3
      - --enable-versioned-symbols
    build-packages:
      - wget
      - libssl-dev
      - libgnutls28-dev
      - libssh2-1-dev
      - libbrotli-dev
      - libidn2-dev
      - librtmp-dev
      - libldap2-dev
      - libnghttp2-dev
      - libpsl-dev
      - libkrb5-dev
      - libzstd-dev
    stage-packages:
      - libbrotli1
      - libidn2-0
      - librtmp1
      - libldap2
      - libssh2-1t64
      - libnghttp2-14
      - libpsl5t64
      - libkrb5-3
      - libzstd1

  # openssl:
  #   plugin: nil
  #   override-pull: |
  #     wget https://github.com/openssl/openssl/releases/download/openssl-3.4.0/openssl-3.4.0.tar.gz -O openssl-src.tar.gz
  #     tar zxf openssl-src.tar.gz --strip-components=1
  #     rm -f openssl-src.tar.gz
  #   override-build: |
  #     ./config --prefix=/usr/local --libdir=lib
  #     make && make install
  #   build-packages:
  #     - wget
  #     - pkg-config

  # nghttp3:
  #   after: [openssl]
  #   plugin: autotools
  #   source: https://github.com/ngtcp2/nghttp3
  #   source-type: git
  #   source-tag: 'v1.7.0'
  #   source-depth: 1
  #   autotools-configure-parameters:
  #     - --enable-lib-only
  #   build-packages:
  #     - pkg-config
